import type { Metadata } from "next";
import Container from "@/components/container";
import ThemeToggle from "@/components/theme-toggle";
import Navigation from "@/components/navigation";
import Card from "@/components/card";
import Icon from "@/components/icon";

import TomsOffroadLogo from "@/components/logos/toms-offroad";
import GatorWadersLogo from "@/components/logos/gator-waders";
import B2BTransportationLogo from "@/components/logos/b2b-transportation";
import BallisticArmorCoLogo from "@/components/logos/ballistic-armor-co";
import EnergyBrosLogo from "@/components/logos/energy-bros";
import JBSteelLogo from "@/components/logos/jb-steel";
import OregonTruckAutoLogo from "@/components/logos/oregon-truck-auto";
import CitiBankLogo from "@/components/logos/citi-bank";
import HighwayProductsLogo from "@/components/logos/highway-products";
import TIAALogo from "@/components/logos/tiaa";
import OperationWarmLogo from "@/components/logos/operation-warm";
import NICIndustriesLogo from "@/components/logos/nic-industries";
import ChinookWindsLogo from "@/components/logos/chinook-winds";
import TangleFreeLogo from "@/components/logos/tanglefree";
import PlannedParenthoodLogo from "@/components/logos/planned-parenthood";

import projects from "@/data/projects";

export const metadata: Metadata = {
  title: "Sebastian Inman",
  description: "Generated by create next app"
};

export default function Home() {
  return (
    <>
      <Container>
        <aside className="lg:sticky top-0 lg:h-dvh lg:py-22 flex flex-col justify-between lg:max-w-[410px]">
          <div className="relative flex flex-col">
            {/* <span className="relative overflow-clip inline-flex rounded-full text-sm font-medium">
              <span className="relative z-10 inline-flex items-center py-1 pl-2.5 pr-5">
                <span className="mr-2 text-base">😜</span>
                <span className="text-white leading-none">Available for hire</span>
              </span>
              <span className="absolute inset-0 bg-sky-500/20 -z-10 animate-pulse" />
            </span> */}
            <ThemeToggle />
            {/* <div className="order-2 lg:order-1 aspect-3/1 lg:aspect-2/1 w-full lg:rounded-sm overflow-hidden mt-6 flex flex-col">
              <div className="flex-1 bg-[#fcb622]" />
              <div className="flex-1 bg-[#ff642c]" />
              <div className="flex-1 bg-[#ed212f]" />
              <div className="flex-1 bg-[#bd2140]" />
              <div className="flex-1 bg-[#692153]" />
            </div> */}
            <div className="relative overflow-hidden rounded-sm grid aspect-3/2 mt-6 lg:mt-0">
              <img src="/me.jpeg" alt="Sebastian Inman" className="size-full object-fill saturate-0 dark:contrast-110" />
            </div>
            <div className="order-1 lg:order-2">
              <div className="relative flex flex-col justify-end">
                {/* <div className="absolute bottom-0 flex flex-col gap-1 justify-end w-full pointer-events-none lg:pb-4.5">
                  <span className="transition-colors h-0.5 w-full bg-background" />
                  <span className="transition-colors h-0.5 w-full bg-background" />
                  <span className="transition-colors h-0.5 w-full bg-background" />
                  <span className="transition-colors h-0.5 w-full bg-background" />
                </div> */}
                <h1 className="text-heading text-3xl lg:text-6xl font-bold leading-none mt-6">
                  Sebastian Inman
                </h1>
              </div>
              <h2 className="text-heading text-base lg:text-lg font-semibold leading-tight">
                Senior Enterprise Web Systems Engineer
              </h2>
            </div>
            <div className="order-3 mt-6 space-y-4">
              {/* <p>
                I'm a senior engineer specializing in enterprise-grade web
                platforms, design systems, and TypeScript-first architecture.
              </p> */}
              <p>
                I help teams move beyond one-off projects and ad-hoc components
                into coherent systems: shared monorepos, reusable UI libraries,
                and well-structured foundations that can support multiple
                products and brands over time.
              </p>
            </div>
            <Navigation className="order-4" />
          </div>
          <div className="flex items-center w-full mt-8 lg:mt-[72px]">
            {/* <div className="size-12 mr-8 rounded-full overflow-clip">
              <img
                src="/apple-touch-icon.png"
                alt="Sebastian Inman"
                className="size-12 rounded-full"
              />
            </div> */}
            <ul className="flex -mx-4 text-heading">
              <li className="mx-4">
                <a
                  className="flex items-center"
                  href="https://www.linkedin.com/in/sebastianinman/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Icon name="linkedin" className="mr-4" />
                  <span className="mt-px leading-none">LinkedIn</span>
                  <Icon name="external" className="size-3! ml-2" />
                </a>
              </li>
              <li className="mx-4">
                <a
                  className="flex items-center"
                  href="https://github.com/inman-sebastian"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Icon name="github" className="mr-4" />
                  <span className="mt-px leading-none">GitHub</span>
                  <Icon name="external" className="size-3! ml-2" />
                </a>
              </li>
            </ul>
          </div>
        </aside>
        <main className="flex-1 flex flex-col lg:pt-22">
          <section
            id="projects"
            aria-labelledby="projects-heading"
            className="lg:pt-22 lg:-mt-24"
          >
            <h2
              id="projects-heading"
              className="sticky top-0 z-40 pt-6 text-sm font-bold tracking-widest uppercase lg:sr-only text-heading"
            >
              Projects
            </h2>
            <div className="group grid grid-cols-1">
              {projects.map((project) => (
                <Card
                  key={project.href}
                  href={project.href}
                  type="project"
                  primaryLanguage={project.primaryLanguage}
                  title={project.title}
                  description={project.description}
                  className="my-1"
                />
              ))}
            </div>
          </section>
          <section
            id="clients"
            aria-labelledby="clients-heading"
            className="lg:mt-22"
          >
            <h2
              id="clients-heading"
              className="sticky top-0 z-40 pt-6 text-sm font-bold tracking-widest uppercase lg:sr-only text-heading"
            >
              Clients
            </h2>
            <div className="group grid grid-cols-2 lg:grid-cols-3 gap-2 place-items-center text-heading">
              <Card>
                <CitiBankLogo className="h-10 lg:h-15" />
              </Card>
              <Card>
                <TIAALogo className="h-10 lg:h-15" />
              </Card>
              <Card>
                <PlannedParenthoodLogo className="h-10 lg:h-15" />
              </Card>
              <Card>
                <OperationWarmLogo className="h-10 lg:h-15" />
              </Card>
              <Card>
                <ChinookWindsLogo className="h-10 lg:h-15" />
              </Card>
              <Card>
                <TangleFreeLogo className="h-10 lg:h-15" />
              </Card>
              <Card>
                <NICIndustriesLogo className="h-10 lg:h-15" />
              </Card>
              <Card>
                <TomsOffroadLogo className="h-10 lg:h-15" />
              </Card>
              <Card>
                <JBSteelLogo className="h-10 lg:h-15" />
              </Card>
              <Card>
                <GatorWadersLogo className="h-10 lg:h-15" />
              </Card>
              <Card>
                <B2BTransportationLogo className="h-10 lg:h-15" />
              </Card>
              <Card>
                <BallisticArmorCoLogo className="h-10 lg:h-15" />
              </Card>
              <Card>
                <EnergyBrosLogo className="h-10 lg:h-15" />
              </Card>
              <Card>
                <OregonTruckAutoLogo className="h-10 lg:h-15" />
              </Card>
              <Card>
                <HighwayProductsLogo className="h-10 lg:h-15" />
              </Card>
            </div>
          </section>
          <section
            id="thoughts"
            aria-labelledby="thoughts-heading"
            className="lg:mt-22"
          >
            <h2
              id="thoughts-heading"
              className="sticky top-0 z-40 pt-6 text-sm font-bold tracking-widest uppercase lg:sr-only text-heading"
            >
              Thoughts
            </h2>
            <div className="group grid grid-cols-1 lg:grid-cols-2 pt-8 pb-10 gap-2 lg:py-0">
              <Card
                href="/thoughts/thought-1"
                type="thought"
                primaryTopic="Front-End"
                datePublished="November 27, 2025"
                title="Proident elit consequat cupidatat eiusmod aliqua cillum"
                className="min-h-80"
              />
              <Card
                href="/thoughts/thought-2"
                type="thought"
                primaryTopic="Front-End"
                datePublished="November 27, 2025"
                title="Proident elit consequat cupidatat eiusmod aliqua cillum"
                className="min-h-80"
              />
              <Card
                href="/thoughts/thought-3"
                type="thought"
                primaryTopic="Front-End"
                datePublished="November 27, 2025"
                title="Proident elit consequat cupidatat eiusmod aliqua cillum"
                className="min-h-80"
              />
              <Card
                href="/thoughts/thought-4"
                type="thought"
                primaryTopic="Front-End"
                datePublished="November 27, 2025"
                title="Proident elit consequat cupidatat eiusmod aliqua cillum"
                className="min-h-80"
              />
              <Card
                href="/thoughts/thought-5"
                type="thought"
                primaryTopic="Front-End"
                datePublished="November 27, 2025"
                title="Proident elit consequat cupidatat eiusmod aliqua cillum"
                className="min-h-80"
              />
            </div>
          </section>
          <section
            id="experiments"
            aria-labelledby="experiments-heading"
            className="lg:mt-22"
          >
            <h2
              id="experiments-heading"
              className="sticky top-0 z-40 pt-6 text-sm font-bold tracking-widest uppercase lg:sr-only text-heading"
            >
              experiments
            </h2>
          </section>
        </main>
      </Container>
    </>
  );
}
