import type { Metadata } from "next";
import Container from "@/components/container";
import ThemeToggle from "@/components/theme-toggle";
import Navigation from "@/components/navigation";
import Card from "@/components/card";
import Icon from "@/components/icon";

export const metadata: Metadata = {
  title: "Sebastian Inman",
  description: "Generated by create next app"
};

export default function Home() {
  return (
    <>
      <Container>
        <aside className="lg:sticky top-0 lg:h-screen lg:py-16 flex flex-col justify-between lg:max-w-[410px]">
          <div>
            {/* <span className="relative overflow-clip inline-flex rounded-full text-sm font-medium">
              <span className="relative z-10 inline-flex items-center py-1 pl-2.5 pr-5">
                <span className="mr-2 text-base">😜</span>
                <span className="text-white leading-none">Available for hire</span>
              </span>
              <span className="absolute inset-0 bg-sky-500/20 -z-10 animate-pulse" />
            </span> */}
            <ThemeToggle />
            <h1 className="text-heading text-3xl lg:text-6xl font-bold leading-none mt-6">Sebastian Inman</h1>
            <h2 className="text-heading text-base lg:text-lg font-semibold leading-tight mt-3">Senior Enterprise Web Systems Engineer</h2>
            <div className="mt-6 space-y-4">
              <p>I'm a senior engineer specializing in enterprise-grade web platforms, design systems, and TypeScript-first architecture.</p>
              <p>I help teams move beyond one-off projects and ad-hoc components into coherent systems: shared monorepos, reusable UI libraries, and well-structured foundations that can support multiple products and brands over time.</p>
            </div>
            <Navigation />
          </div>
          <div className="flex items-center w-full mt-8 lg:mt-[72px]">
            <div className="size-12 mr-8 rounded-full overflow-clip">
              <img src="/apple-touch-icon.png" alt="Sebastian Inman" className="size-12 rounded-full" />
            </div>
            <ul className="flex -mx-4 text-heading">
              <li className="mx-4">
                <a className="flex items-center" href="https://www.linkedin.com/in/sebastianinman/" target="_blank" rel="noopener noreferrer">
                  <Icon name="linkedin" className="mr-4" />
                  <span className="mt-px leading-none">LinkedIn</span>
                  <Icon name="external" className="size-3! ml-2" />
                </a>
              </li>
              <li className="mx-4">
                <a className="flex items-center" href="https://github.com/inman-sebastian" target="_blank" rel="noopener noreferrer">
                  <Icon name="github" className="mr-4" />
                  <span className="mt-px leading-none">GitHub</span>
                  <Icon name="external" className="size-3! ml-2" />
                </a>
              </li>
            </ul>
          </div>
        </aside>
        <main className="flex-1 lg:min-h-screen flex flex-col lg:py-24 lg:pl-42">
          <section id="projects" aria-labelledby="projects-heading" className="lg:pt-22 lg:-mt-24">
            <h2 id="projects-heading" className="sticky top-0 z-40 pt-6 text-sm font-bold tracking-widest uppercase lg:sr-only text-heading">Projects</h2>
            <div className="group grid grid-cols-1 pt-8 pb-10 -my-1 lg:py-0">
              <Card href="https://github.com/inman-sebastian/pizzatime"
                type="project"
                primaryLanguage="typescript"
                title="🍕 pizzatime"
                description="Sometimes when you're in the middle of coding, you just need a break to order some pizza. The pizzatime CLI tool helps you do just that without ever having to leave your terminal."
                className="my-1" />
              <Card href="/projects/project-2"
                type="project"
                primaryLanguage="typescript"
                title="Project Two"
                description="Veniam mollit Lorem ipsum aute exercitation excepteur aute occaecat nulla ad aliqua quis occaecat. In officia culpa in labore minim."
                className="my-1" />
              <Card href="/projects/project-3"
                type="project"
                primaryLanguage="typescript"
                title="Project Three"
                description="Veniam mollit Lorem ipsum aute exercitation excepteur aute occaecat nulla ad aliqua quis occaecat. In officia culpa in labore minim."
                className="my-1" />
              <Card href="/projects/project-4"
                type="project"
                primaryLanguage="typescript"
                title="Project Four"
                description="Veniam mollit Lorem ipsum aute exercitation excepteur aute occaecat nulla ad aliqua quis occaecat. In officia culpa in labore minim."
                className="my-1" />
            </div>
          </section>
          <section id="thoughts" aria-labelledby="thoughts-heading" className="lg:mt-22">
            <h2 id="thoughts-heading" className="sticky top-0 z-40 pt-6 text-sm font-bold tracking-widest uppercase lg:sr-only text-heading">Thoughts</h2>
            <div className="group grid grid-cols-1 lg:grid-cols-2 pt-8 pb-10 -my-1 lg:py-0">
              <Card href="/thoughts/thought-1" 
                type="thought" 
                primaryTopic="Front-End" 
                datePublished="November 27, 2025" 
                title="Proident elit consequat cupidatat eiusmod aliqua cillum" 
                className="my-1 lg:m-1 min-h-80" />
              <Card href="/thoughts/thought-2" 
                type="thought" 
                primaryTopic="Front-End" 
                datePublished="November 27, 2025" 
                title="Proident elit consequat cupidatat eiusmod aliqua cillum" 
                className="my-1 lg:m-1 min-h-80" />
              <Card href="/thoughts/thought-3" 
                type="thought" 
                primaryTopic="Front-End" 
                datePublished="November 27, 2025" 
                title="Proident elit consequat cupidatat eiusmod aliqua cillum" 
                className="my-1 lg:m-1 min-h-80" />
              <Card href="/thoughts/thought-4" 
                type="thought" 
                primaryTopic="Front-End" 
                datePublished="November 27, 2025" 
                title="Proident elit consequat cupidatat eiusmod aliqua cillum" 
                className="my-1 lg:m-1 min-h-80" />
              <Card href="/thoughts/thought-5" 
                type="thought" 
                primaryTopic="Front-End" 
                datePublished="November 27, 2025" 
                title="Proident elit consequat cupidatat eiusmod aliqua cillum" 
                className="my-1 lg:m-1 min-h-80" />
            </div>
          </section>
          <section id="playground" aria-labelledby="playground-heading" className="lg:mt-22">
            <h2 id="playground-heading" className="sticky top-0 z-40 pt-6 text-sm font-bold tracking-widest uppercase lg:sr-only text-heading">Playground</h2>
          </section>
        </main>
      </Container>
    </>
  );
}
